apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "alejo-ionix.fullname" . }}
  labels:
    {{- include "alejo-ionix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alejo-ionix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alejo-ionix.selectorLabels" . | nindent 8 }}
    spec:
      securityContext: # this applies the security settings to all containers in the pod
        #unAsUser: 1001
        #runAsGroup: 101
        #fsGroup: 101
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: alejo-ionix-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      volumes:
        - name: alejo-ionix-config
          configMap:
            name: {{ template "alejo-ionix.fullname" . }}