apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "alejo-ionix.fullname" . }}
  labels:
    {{- include "alejo-ionix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alejo-ionix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alejo-ionix.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          securityContext: # this applies the security settings to all containers in the pod
            # readOnlyRootFilesystem: true
            # runAsUser: 1000
            # runAsNonRoot: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: alejo-ionix-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      volumes:
        - name: alejo-ionix-config
          configMap:
            name: {{ template "alejo-ionix.fullname" . }}