image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

configMap:
  index.html: |
    <html>
      <body>
        <h1>Hola Mundo!</h1>
      </body>
    </html>

replicaCount: 3

podAnnotations: {}

podLabels: {}